# ruff.toml — standalone config

line-length = 88
target-version = "py311"
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    ".venv",
    "venv",
    "node_modules",
    "site-packages",
]

[lint]
select = ["E", "F", "B", "W", "C90"]
ignore = [
    "E501",  # Line too long
    "E401",  # Multiple imports on one line
    "E402",  # Module level import not at top of file
    "C901",  # Function is too complex
    "F841",  # Unused local variable
    "F821",  # Undefined name
    "B905",  # zip() without strict=
    "B904",  # exception context not chained
    "F811",  # Redefinition of unused name
    "B007",  # Loop control variable not used
    "B012",  # return inside finally
    "E722",  # Do not use bare 'except'
    "E741",  # Ambiguous variable name
    "E701",  # Multiple statements on one line (colon)
    "E702",  # Multiple statements on one line (semicolon)
    "F401",
]
fixable = ["ALL"]
unfixable = []

[lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]
"*/tests/*" = ["D", "S101"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

