"""Compatibility facade for the decomposed shader-graph analysis pipeline."""

from .shader_graph_analysis import (
    MaterialGraphAnalysisResult,
    analyse_material_graph,
    analyse_material_graph_detailed,
)
from .shader_graph_error import MaterialGraphAnalysisError
from .shader_graph_rna import (
    TEMPORARY_PREFIXES as _TEMPORARY_PREFIXES,
    VALID_RENDER_TARGETS as _VALID_RENDER_TARGETS,
    color_nonzero as _color_nonzero,
    find_active_node as _find_active_node,
    find_material_output as _find_material_output,
    first_input_socket as _first_input_socket,
    input_socket as _input_socket,
    is_temporary_node as _is_temporary_node,
    iter_collection as _iter_collection,
    iter_links as _iter_links,
    iter_nodes as _iter_nodes,
    matching_socket as _matching_socket,
    material_name as _material_name,
    node_name as _node_name,
    node_output_target as _node_output_target,
    node_type as _node_type,
    normalise_render_target as _normalise_render_target,
    numeric_default as _numeric_default,
    rna_identity as _rna_identity,
    same_socket as _same_socket,
    socket_by_name as _socket_by_name,
    socket_enabled as _socket_enabled,
    socket_identifier as _socket_identifier,
    socket_index as _socket_index,
    socket_name as _socket_name,
    tree_name as _tree_name,
)
from .shader_graph_semantics import (
    CAMERA_SHADER_TYPES as _CAMERA_SHADER_TYPES,
    GEOMETRY_NODE_TYPES as _GEOMETRY_NODE_TYPES,
    OBJECT_NODE_TYPES as _OBJECT_NODE_TYPES,
    SCENE_LIGHTING_SHADER_TYPES as _SCENE_LIGHTING_SHADER_TYPES,
    SURFACE_SHADER_TYPES as _SURFACE_SHADER_TYPES,
    VIEW_NODE_TYPES as _VIEW_NODE_TYPES,
    derive_material_dependencies as _dependencies,
    derive_semantic_channels as _semantic_channels,
    principled_alpha_enabled as _principled_alpha_enabled,
    principled_dependencies as _principled_dependencies,
    principled_emission_enabled as _principled_emission_enabled,
)
from .shader_graph_traversal import (
    GROUP_INPUT_TYPES as _GROUP_INPUT_TYPES,
    GROUP_NODE_TYPES as _GROUP_NODE_TYPES,
    GROUP_OUTPUT_TYPES as _GROUP_OUTPUT_TYPES,
    MAX_GROUP_DEPTH as _MAX_GROUP_DEPTH,
    ReachableShaderNode as _ReachableNode,
    RecursiveShaderGraphWalker as _RecursiveGraphWalker,
    ShaderGraphFrame as _GraphFrame,
    ShaderGraphTraversalResult,
)


__all__ = [
    "MaterialGraphAnalysisError",
    "MaterialGraphAnalysisResult",
    "ShaderGraphTraversalResult",
    "_CAMERA_SHADER_TYPES",
    "_GEOMETRY_NODE_TYPES",
    "_GROUP_INPUT_TYPES",
    "_GROUP_NODE_TYPES",
    "_GROUP_OUTPUT_TYPES",
    "_GraphFrame",
    "_MAX_GROUP_DEPTH",
    "_OBJECT_NODE_TYPES",
    "_ReachableNode",
    "_RecursiveGraphWalker",
    "_SCENE_LIGHTING_SHADER_TYPES",
    "_SURFACE_SHADER_TYPES",
    "_TEMPORARY_PREFIXES",
    "_VALID_RENDER_TARGETS",
    "_VIEW_NODE_TYPES",
    "_color_nonzero",
    "_dependencies",
    "_find_active_node",
    "_find_material_output",
    "_first_input_socket",
    "_input_socket",
    "_is_temporary_node",
    "_iter_collection",
    "_iter_links",
    "_iter_nodes",
    "_matching_socket",
    "_material_name",
    "_node_name",
    "_node_output_target",
    "_node_type",
    "_normalise_render_target",
    "_numeric_default",
    "_principled_alpha_enabled",
    "_principled_dependencies",
    "_principled_emission_enabled",
    "_rna_identity",
    "_same_socket",
    "_semantic_channels",
    "_socket_by_name",
    "_socket_enabled",
    "_socket_identifier",
    "_socket_index",
    "_socket_name",
    "_tree_name",
    "analyse_material_graph",
    "analyse_material_graph_detailed",
]
