"""Application use-case contracts for the rewrite pipeline."""

from .a1_attachment_projection_service import (
    A1AttachmentProjectionError,
    A1AttachmentProjectionResult,
    A1AttachmentProjectionSettings,
    A1AttachmentVertexKey,
    A1VertexZBinding,
    project_triangulated_disk_attachment,
)
from .a1_camera_projection import (
    assemble_a1_camera_projection_document,
    build_camera_projection_mesh_snapshot,
    build_camera_projection_quad_snapshot,
)
from .a1_document_assembly import (
    A1DocumentAssemblyError,
    A1DocumentAssemblyResult,
    A1DocumentAssemblySettings,
    assemble_a1_document,
)
from .a1_export_readiness import (
    A1ExportReadinessReport,
    A1ObjectReadiness,
    A1ReadinessState,
    ReadinessStatistic,
)
from .a1_generated_materials import (
    build_generated_material_plan,
    generated_palette_color,
)
from .a1_geometry_preparation import (
    A1GeometryPreparationError,
    A1GeometryPreparationResult,
    A1GeometryPreparationSettings,
    A1PreparedRegion,
    prepare_a1_geometry_regions,
)
from .a1_grouped_camera_projection import (
    GroupedCameraOverlayError,
    GroupedCameraOverlayResult,
    apply_grouped_camera_overlay,
)
from .a1_multi_object import (
    A1MultiObjectExportSettings,
    A1MultiObjectMode,
    A1MultiObjectStage,
    ConnectedCameraRenderPolicy,
    resolve_a1_multi_object_preparation_settings,
)
from .a1_object_bake_placement import calculate_a1_object_bake_main_position_pixels
from .a1_single_object import (
    A1MeshBounds,
    A1ResolvedOutputPaths,
    A1SingleObjectExportSettings,
    A1SingleObjectStage,
    A1SourceGeometryMode,
    A1SourceUvBoundaryMode,
    build_a1_attachment_path,
    build_a1_attachment_sequence,
    build_a1_bake_settings,
    calculate_a1_main_position_pixels,
    calculate_a1_mesh_bounds,
    resolve_a1_names,
    resolve_a1_output_paths,
)
from .a1_output_preflight import (
    A1OutputNamespacePreflight,
    A1OutputPathClaim,
    A1OutputPathKind,
    A1OutputPreflightSource,
    preflight_a1_output_namespace,
    validate_a1_output_claims,
    validate_a1_realized_output_namespace,
)
from .a1_texturing_layout import (
    A1TexturingLayoutError,
    A1TexturingTopology,
    A1UvPropagationResult,
    A1UvReadyRegion,
    build_a1_texturing_topology,
    propagate_texturing_uv_to_regions,
)
from .a1_z_groups import (
    A1SourceVertexZBinding,
    A1ZGroupAssignmentError,
    A1ZGroupAssignmentPlan,
    A1ZGroupHeightOverride,
    build_a1_z_group_assignment,
)
from .contracts import (
    ExportIssue,
    ExportRequest,
    ExportResult,
    ExportSettings,
    IssueSeverity,
)

__all__ = [
    "A1AttachmentProjectionError",
    "A1AttachmentProjectionResult",
    "A1AttachmentProjectionSettings",
    "A1AttachmentVertexKey",
    "A1DocumentAssemblyError",
    "A1DocumentAssemblyResult",
    "A1DocumentAssemblySettings",
    "A1ExportReadinessReport",
    "A1GeometryPreparationError",
    "A1GeometryPreparationResult",
    "A1GeometryPreparationSettings",
    "A1MeshBounds",
    "A1MultiObjectExportSettings",
    "A1MultiObjectMode",
    "A1MultiObjectStage",
    "A1ObjectReadiness",
    "A1OutputNamespacePreflight",
    "A1OutputPathClaim",
    "A1OutputPathKind",
    "A1OutputPreflightSource",
    "A1PreparedRegion",
    "A1ReadinessState",
    "A1ResolvedOutputPaths",
    "A1SingleObjectExportSettings",
    "A1SingleObjectStage",
    "A1SourceGeometryMode",
    "A1SourceUvBoundaryMode",
    "A1SourceVertexZBinding",
    "A1TexturingLayoutError",
    "A1TexturingTopology",
    "A1UvPropagationResult",
    "A1UvReadyRegion",
    "A1VertexZBinding",
    "A1ZGroupAssignmentError",
    "A1ZGroupAssignmentPlan",
    "A1ZGroupHeightOverride",
    "ConnectedCameraRenderPolicy",
    "ExportIssue",
    "ExportRequest",
    "ExportResult",
    "ExportSettings",
    "GroupedCameraOverlayError",
    "GroupedCameraOverlayResult",
    "IssueSeverity",
    "ReadinessStatistic",
    "apply_grouped_camera_overlay",
    "assemble_a1_camera_projection_document",
    "assemble_a1_document",
    "build_a1_attachment_path",
    "build_a1_attachment_sequence",
    "build_a1_bake_settings",
    "build_a1_texturing_topology",
    "build_a1_z_group_assignment",
    "build_camera_projection_mesh_snapshot",
    "build_camera_projection_quad_snapshot",
    "build_generated_material_plan",
    "calculate_a1_main_position_pixels",
    "calculate_a1_mesh_bounds",
    "calculate_a1_object_bake_main_position_pixels",
    "generated_palette_color",
    "preflight_a1_output_namespace",
    "prepare_a1_geometry_regions",
    "project_triangulated_disk_attachment",
    "propagate_texturing_uv_to_regions",
    "resolve_a1_multi_object_preparation_settings",
    "resolve_a1_names",
    "resolve_a1_output_paths",
    "validate_a1_output_claims",
    "validate_a1_realized_output_namespace",
]
