#!/usr/bin/env python3
"""Compare a legacy Spine JSON export with a rewritten A1 export.

Exit codes:
    0: compatible under the selected parity policy;
    1: comparison completed and found one or more compatibility errors;
    2: arguments, input files, or JSON content are invalid.
"""

from __future__ import annotations

import argparse
from dataclasses import asdict
import json
from pathlib import Path
import sys
from typing import Any, Mapping, Sequence


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from Blender_to_Spine2D_Mesh_Exporter.domain.spine import (  # noqa: E402
    A1ParityIssue,
    A1ParityReport,
    A1ParitySettings,
    compare_a1_exports,
)


EXIT_COMPATIBLE = 0
EXIT_INCOMPATIBLE = 1
EXIT_INVALID_INPUT = 2


def _positive_or_zero_float(value: str) -> float:
    try:
        resolved = float(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"Expected a number, got {value!r}") from exc
    if resolved < 0.0:
        raise argparse.ArgumentTypeError("Value cannot be negative")
    return resolved


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Compare a v0.23 legacy Spine JSON export with an A1 rewrite export "
            "using structural, mesh, and weighted-bone semantics."
        )
    )
    parser.add_argument(
        "expected",
        type=Path,
        help="Legacy/v0.23 Spine JSON used as the golden reference",
    )
    parser.add_argument(
        "actual",
        type=Path,
        help="Spine JSON generated by the rewritten A1 pipeline",
    )
    parser.add_argument(
        "--absolute-tolerance",
        type=_positive_or_zero_float,
        default=1e-4,
        help="Absolute floating-point tolerance (default: 1e-4)",
    )
    parser.add_argument(
        "--relative-tolerance",
        type=_positive_or_zero_float,
        default=1e-6,
        help="Relative floating-point tolerance (default: 1e-6)",
    )
    parser.add_argument(
        "--compare-animations",
        action="store_true",
        help="Compare the animations section in addition to setup data",
    )
    parser.add_argument(
        "--strict-edges",
        action="store_true",
        help="Treat nonessential mesh edge differences as errors instead of warnings",
    )
    parser.add_argument(
        "--ignore-path",
        action="append",
        default=[],
        metavar="PATTERN",
        help=(
            "Additional fnmatch-style comparison path to ignore. May be supplied "
            "more than once."
        ),
    )
    parser.add_argument(
        "--report-json",
        type=Path,
        default=None,
        help="Optional path for a machine-readable comparison report",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Print only the final status line",
    )
    return parser


def _load_json_mapping(path: Path, label: str) -> Mapping[str, Any]:
    if not isinstance(path, Path):
        raise TypeError("path must be pathlib.Path")
    resolved = path.expanduser().resolve(strict=False)
    if not resolved.is_file():
        raise ValueError(f"{label} file does not exist: {resolved}")
    try:
        text = resolved.read_text(encoding="utf-8-sig")
    except OSError as exc:
        raise ValueError(f"Unable to read {label} file {resolved}: {exc}") from exc
    try:
        value = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"{label} file is not valid JSON at line {exc.lineno}, "
            f"column {exc.colno}: {exc.msg}"
        ) from exc
    if not isinstance(value, Mapping):
        raise ValueError(f"{label} JSON root must be an object")
    return value


def _issue_mapping(issue: A1ParityIssue) -> dict[str, Any]:
    return {
        "severity": issue.severity.value,
        "code": issue.code,
        "path": issue.path,
        "message": issue.message,
        "expected": issue.expected,
        "actual": issue.actual,
    }


def _report_mapping(
    report: A1ParityReport,
    expected_path: Path,
    actual_path: Path,
) -> dict[str, Any]:
    return {
        "compatible": report.compatible,
        "error_count": report.error_count,
        "warning_count": report.warning_count,
        "expected_file": str(expected_path.expanduser().resolve(strict=False)),
        "actual_file": str(actual_path.expanduser().resolve(strict=False)),
        "settings": asdict(report.settings),
        "expected_fingerprint_digest": (
            None
            if report.expected_fingerprint is None
            else report.expected_fingerprint.digest()
        ),
        "actual_fingerprint_digest": (
            None
            if report.actual_fingerprint is None
            else report.actual_fingerprint.digest()
        ),
        "issues": [_issue_mapping(issue) for issue in report.issues],
    }


def _write_report_json(path: Path, payload: Mapping[str, Any]) -> None:
    resolved = path.expanduser().resolve(strict=False)
    try:
        resolved.parent.mkdir(parents=True, exist_ok=True)
        temporary = resolved.with_name(f".{resolved.name}.tmp")
        temporary.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        temporary.replace(resolved)
    except OSError as exc:
        raise ValueError(f"Unable to write report JSON {resolved}: {exc}") from exc


def _format_value(value: Any, *, limit: int = 240) -> str:
    text = repr(value)
    if len(text) <= limit:
        return text
    return text[: limit - 3] + "..."


def _print_human_report(report: A1ParityReport, *, quiet: bool) -> None:
    status = "COMPATIBLE" if report.compatible else "INCOMPATIBLE"
    if quiet:
        print(
            f"A1 golden parity: {status} "
            f"({report.error_count} errors, {report.warning_count} warnings)"
        )
        return

    print(f"A1 golden parity: {status}")
    print(f"Errors: {report.error_count}")
    print(f"Warnings: {report.warning_count}")
    if report.expected_fingerprint is not None:
        print(f"Expected structure: {report.expected_fingerprint.digest()}")
    if report.actual_fingerprint is not None:
        print(f"Actual structure:   {report.actual_fingerprint.digest()}")

    if not report.issues:
        print("No differences detected under the selected policy.")
        return

    print("\nDifferences:")
    for index, issue in enumerate(report.issues, start=1):
        print(
            f"{index}. [{issue.severity.value}] [{issue.code}] "
            f"{issue.path}: {issue.message}"
        )
        if issue.expected is not None:
            print(f"   expected: {_format_value(issue.expected)}")
        if issue.actual is not None:
            print(f"   actual:   {_format_value(issue.actual)}")


def run(arguments: Sequence[str] | None = None) -> int:
    parser = _build_parser()
    namespace = parser.parse_args(arguments)

    try:
        expected = _load_json_mapping(namespace.expected, "expected")
        actual = _load_json_mapping(namespace.actual, "actual")
        defaults = A1ParitySettings()
        settings = A1ParitySettings(
            absolute_tolerance=namespace.absolute_tolerance,
            relative_tolerance=namespace.relative_tolerance,
            ignored_paths=defaults.ignored_paths + tuple(namespace.ignore_path),
            compare_animations=namespace.compare_animations,
            nonessential_mesh_edges_are_errors=namespace.strict_edges,
        )
        report = compare_a1_exports(expected, actual, settings)
        payload = _report_mapping(report, namespace.expected, namespace.actual)
        if namespace.report_json is not None:
            _write_report_json(namespace.report_json, payload)
        _print_human_report(report, quiet=namespace.quiet)
        return EXIT_COMPATIBLE if report.compatible else EXIT_INCOMPATIBLE
    except (TypeError, ValueError, OSError) as exc:
        print(f"A1 golden parity input error: {exc}", file=sys.stderr)
        return EXIT_INVALID_INPUT


def main() -> None:
    raise SystemExit(run())


if __name__ == "__main__":
    main()
